# Generated by Django 5.1.3 on 2024-12-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveIntegerField()),
                ('date_of_field', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='others', max_length=25)),
                ('skills', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Balochistan', 'Balochistan'), ('Islamabad', 'Islamabad'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa')], max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_profile_pictures/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='employee_resume/')),
                ('video', models.FileField(blank=True, null=True, upload_to='employee_video/')),
            ],
        ),
    ]
