# Generated by Django 5.1.3 on 2024-12-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_employee_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date_of_field',
            new_name='date_of_birth',
        ),
    ]
